### ISSUE TITLE
Could be extended for video support ?

### ISSUE THREAD

**Issue by jimisens** [IvanMurzak/Unity-ImageLoader#2]
Hi Ivan thank you for this asset!!
I wonder if the package could be extended for videos as well ?
What is the best  way to do so ?

**Comment by IvanMurzak** [comment]
Hey! Yes, I will do the same package for Audio, and another one for Video as only I will have time to do that.

**Comment by jimisens** [comment]
Hi! Excelent! I will try to extend for videos first because I need that for a current project. 
If I'm well, we can use the same DiskCache and MemoryCache scripts right ? Then maybe rename the base class "Media Loader" instead of "ImageLoader" and add some specific functions for videos then for audio clips. I'm right ?

**Comment by jimisens** [comment]
I have some experience with C# but I never had the opportunity to collaborate in GitHub, so I will do my try, then a share to you, ok ? 
i the same way the last week I download your package Unity Theme for the same project. 
At the end I finish recreating the code to support other data types like TMPro font settings... i Will share to you soon.

**Comment by IvanMurzak** [comment]
I want to make dedicated packages, like totally dedicated things that a developer may install separately. This one is `ImageLoader`. Another one will be `AudioLoader` and `VideoLoader`. There are two reasons to have them separate.

1. Common case that a developer needs something one from all of these `...Loader`, so, a good idea to let a developer to install just what they need.
2. `ImageLoader` has a task pool that is executed in a dedicated thread. It works very well, the reason to have a single thread is to not allow to create a conflict while reading and writing images. Video and Audio files will be stored in a different folder, which means it doesn't conflict with each other. As a result, we can download 3 files at the same time without conflicts.

**Comment by IvanMurzak** [comment]
Added **[Unity-AudioLoader](https://github.com/IvanMurzak/Unity-AudioLoader)**

**Comment by jimisens** [comment]
Excellent @IvanMurzak , Thank you

**Comment by IvanMurzak** [comment]
@jimisens hey. I tried to make the package for Video encryption, caching, and sending to Unity's VideoPlayer. Unfortunately, Unity's API doesn't allow setting a data stream or bytes array into `VideoPlayer`, also it doesn't allow creating `VideoClip` from a bytes array. 

That means we lose the ability to implement these features:
❌Cache data encryption
❌Playing video and caching it at the same time

We only can download video twice, once for saving and once for playing. That means video playing could be slowdown because of the second data loading stream in the background. After the fully loaded video of course we can play it without downloading again. But that all already looks broken enough. I found an alternative solution for Unity's `VideoPlayer` that supports caching and streaming. Possibly you may find it useful for your project. Looks promising.
# [NexPlayer](https://github.com/NexPlayer/NexPlayer_Unity_Plugin)
![NexPlayer](https://github.com/NexPlayer/NexPlayer_Unity_Plugin/raw/master/resources/last.png)

**Comment by jimisens** [comment]
Hi Ivan! Thank you very much for your attention and all the information. 
I will use your 2 packages Image Loader and Audio Loader, right now 👍 
Just, it seems you forgot to change "displayName" in the package.json file of the AudioLoader package, it still been Image Loader ?
And for the Video Loader, i understand the Unity's API restrictions.. i confirmed this problem in some forums on the web..
For me is not actually a problem because all the media files will be preloaded before the game starts, then everything will use local files in disk.
So i think i will implement just one function to download the video then save it to disk. And finally tell the local url to the Video Loader in unity
